#pragma once
#include "macro.h"

#include <fltKernel.h>


#pragma warning( disable:4127 4305 4100 4201)


#define _DEVICE_NAME L"\\Device\\"
#define _DEVICE_DOSNAME L"\\DosDevices\\"

#define IOCTL_STOP_ALL				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1001, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_START_ALL				CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1002, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_INTERCEPT_MODE	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1003, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_START_PROCMONITOR		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1004, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAUSE_PROCMONITOR		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1005, METHOD_BUFFERED, FILE_ANY_ACCESS)  
#define IOCTL_START_REGMONITOR		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1006, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAUSE_REGMONITOR		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1007, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_START_FILEMONITOR		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1008, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PAUSE_FILEMONITOR		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1009, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STOP_UNLOAD			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1010, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_PERMIT_UNLOAD			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1011, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_SET_NOTIFY_MODE		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1012, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TRANSFER_SYSROOT		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1013, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_REMOVE_HOOK			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1014, METHOD_BUFFERED, FILE_ANY_ACCESS) 
#define IOCTL_START_SVCMONITOR		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1015, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_STOP_SVCMONITOR		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1016, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_TRANSFER_INJECT_DLL	CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1017, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define	IOCTL_FROM_R3MSG			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x1100, METHOD_BUFFERED, FILE_ANY_ACCESS) 


extern WCHAR						g_port_name[MAXNAMELEN];
extern WCHAR						g_device_name[MAXNAMELEN];
extern WCHAR						g_symbol_name[MAXNAMELEN];
extern PDRIVER_OBJECT				g_driver_obj;
extern PDEVICE_OBJECT				g_device_obj;